baseURL = 'http://localhost/hugo'
languageCode = 'es-es'
title = 'Sitio Hugo de Prueba'
theme = 'tale'

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 2
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 3

 [[menu.main]]
	identifier = "clases"
	name = "Clases"
	title = "Clases"
	url = "/clases/"
	weight = 4
